world_visit = ['africa', 'india', 'italy', 'iceland', 'wales']
print(world_visit)
sorted(world_visit)
print(sorted(world_visit))
print(world_visit)
sorted(world_visit, reverse=True)
world_visit.reverse()
print(world_visit)
world_visit.reverse()
print(world_visit)
world_visit.sort()
print(world_visit)
world_visit.sort(reverse=True)
print(world_visit)
